[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install && node scripts/write-version.js"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
